# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 自动创建
export WORKDIR=~/Documents/work
[ ! -d $WORKDIR ] && mkdir -p $WORKDIR

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.powerlevel10k/powerlevel10k.zsh-theme

autoload -Uz compinit
compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# [ -f ~/.vim/.dircolors ] && source ~/.vim/.dircolors

# Terminal Color Settings
export CLICOLOR=1

export VIRTUALENVWRAPPER_PYTHON=python3
[ -f /opt/homebrew/bin/virtualenvwrapper.sh ] && source /opt/homebrew/bin/virtualenvwrapper.sh

# export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
#

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export ZPLUG_HOME=/opt/homebrew/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "zdharma/fast-syntax-highlighting", as:plugin, defer:2

export PATH=/Users/jade/go/bin:$PATH

awsctx() {
  export AWS_SDK_LOAD_CONFIG=1
  export AWS_PROFILE=$(aws configure list-profiles | fzf)
}
