# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 自动创建
export WORKDIR=~/Documents/work
[ ! -d $WORKDIR ] && mkdir -p $WORKDIR

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.powerlevel10k/powerlevel10k.zsh-theme

autoload -Uz compinit
compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# [ -f ~/.vim/.dircolors ] && source ~/.vim/.dircolors

# Terminal Color Settings
export CLICOLOR=1

export VIRTUALENVWRAPPER_PYTHON=python3
[ -f /opt/homebrew/bin/virtualenvwrapper.sh ] && source /opt/homebrew/bin/virtualenvwrapper.sh

# export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
#

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export ZPLUG_HOME=/opt/homebrew/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "zdharma/fast-syntax-highlighting", as:plugin, defer:2

export GOPATH=$HOME/go
export PATH=/opt/homebrew/opt/curl/bin:/opt/homebrew/sbin:/opt/homebrew/opt/libpq/bin:$GOPATH/bin:/opt/homebrew/opt/go/bin:$PATH
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:/opt/homebrew/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

awsctx() {
  export AWS_SDK_LOAD_CONFIG=1
  export AWS_PROFILE=$(aws configure list-profiles | fzf)
}

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


# for k8s
source <(kubectl completion zsh)

# for nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias ap='ansible-playbook'
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jade/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

. "$HOME/.local/bin/env"
